### ISSUE TITLE
Demos currently not working on iPad (5.1.1) + iPhone (5.1.2) + iPad Simulator (4.3)

### ISSUE THREAD

**Issue by d5e** [furf/jquery-ui-touch-punch#45]
I recently discovered that this plugin has problems right now resulting in "undefined is not a function" errors.

The weird thing is that this behaviour occurs on all Demo's on the site.

I tested with iPhone, iPad and iPad Simulator - no one is working.

I got a screenshot of the Debug log here http://www.uv7.de/ftp/pub/dropbox/10%20um%2018.04.33.png

**Comment by Imajon** [comment]
Hi, 
I have the same probleme.
It doesn t work on safari and firefox too since yesterday.
I was enjoying drag some stuff and sudently it did t work anymore.

Thanks

**Comment by furf** [comment]
Let me guess... you are using the head branch of jQuery - http://code.jquery.com/jquery.min.js

jQuery just upgraded to 1.8 yesterday and that is causing the problem. I am on it.

In the meanwhile, use 1.7.2 instead - http://code.jquery.com/jquery-1.7.2.min.js

**Comment by Imajon** [comment]
Good, 
Yes i use it :-(
Thanks you for the advIce.

**Comment by furf** [comment]
jQuery UI 1.8 uses $.curCSS which was deprecated in jQuery 1.8. jQuery UI 1.9 does not have this dependency. So an alternative solution is to upgrade to jQuery 1.9 pre - http://code.jquery.com/ui/jquery-ui-git.js - but as a pre-release, may have other issues to worry about.

**Comment by furf** [comment]
Since this bug is not related to touchpunch, I am closing this issue. I have created an adapter that seems to resolve the issue - https://gist.github.com/3325231 - include it after jQueryUI and everything should start working again.
